### ISSUE TITLE
GT130

### ISSUE THREAD

**Issue by sricard999** [claudegel/sinope-gt125#13]
Claude,

Do you know if there are issues using this code with the GT-130 ?

Merci
Stéphane

**Comment by claudegel** [comment]
Sorry but I didn't see your post before. No this won't work. Sinope do not use the same method to call the GT130. Port are different.
I'm trying to connect with the GT130 but I'm also waiting for Sinope to publish there api for the GT130. If you suceed to connect to let me know.

I've started a new repository just for the GT130: see sinope-gt130

**Comment by claudegel** [comment]
This will be addressed on Sinope-gt130
