### ISSUE TITLE
"Setup failed" in latest Home Assistant boot.

### ISSUE THREAD

**Issue by CoryAlbrecht** [claudegel/sinope-gt125#41]
Copied from HomeAssistant logs
```
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 5 May 2021, 19:09:41 (1 occurrences)
Last logged: 5 May 2021, 19:09:41

Setup failed for sinope: Unable to import component: cannot import name 'Astral' from 'astral' (/usr/local/lib/python3.8/site-packages/astral/__init__.py)
```

## System Health

version | core-2021.5.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.0-72-generic
arch | x86_64
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4775
Installed Version | 1.12.3
Stage | running
Available Repositories | 842
Installed Repositories | 37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.2 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 20.10.2
disk_total | 30.9 GB
disk_used | 12.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.7.1), Home Assistant Google Drive Backup (0.104.2), Terminal & SSH (9.1.1), Let's Encrypt (4.11.0), File editor (5.3.0), ADB - Android Debug Bridge (0.8.0), Node-RED (9.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 32
views | 4
mode | storage

</details>

**Comment by CoryAlbrecht** [comment]
Looks like the update now available by HACS fixes the issue

**Comment by olivierjag2** [comment]
I have the same issue :(

**Comment by claudegel** [comment]
Sorry didn't see your message. This was fixed few minutes after I've updated HA. My last release fix it. Hope it is ok with you
