### ISSUE TITLE
Warning timeouts with one v e r y slow thermostat

### ISSUE THREAD

**Issue by danielbrunt57** [claudegel/sinope-gt125#48]
Is there a way to increase the response wait time?
```
2022-02-17 21:40:48 WARNING (SyncWorker_29) [custom_components.neviweb.climate] Cannot update neviweb climate Angela: {'error': {'code': 'DVCCOMMTO', 'data': {'retry': 2}}}. Device is busy or does not respond quickly enough.
```
In Neviweb app, it does report but is very slow.  It also does update to changes from HA but it does take it's sweet time!  I will see if I can relocate the hub but that won't be easy.  They are in opposite corners of the townhouse and on different floors (main level vs upstairs).

**Comment by claudegel** [comment]
Sorry I was busy on neviweb130. I'll check if it is possible to increase time-out wait time. But I think it is set in HA.
Let me check what I can do. Maybe I can resend the request if I find that DVCCOMMTO message.
Note that you posted that issue in sinope-gt125, direct connection to GT125, and it should go in sinope-1, connection via Neviweb

**Comment by claudegel** [comment]
go to https://github.com/claudegel/sinope-1/tree/timeout and copy file climate.py into your 
custom-components/neviweb/ dir
when Neviweb reply with DVCCOMMTO, HA should retry to data update.
Let me know if it work

**Comment by claudegel** [comment]
Another thing you can try is to re-pair your miwi devices starting with the one closest to the GT125 and going farther. The neviweb device try to connect directly to the GT125 but they also can use another miwi devices as a relay. If your slow device was added first then it cannot goes via another miwi device to contact or receive something from the GT125. I don't think it is a too short timeout delay but just the device that do not receive the request fro Neviweb. My patch will just resend the request another time.

**Comment by danielbrunt57** [comment]
Thanks.  I'll  try repairing them this weekend...

**Comment by claudegel** [comment]
Try my patch also. resend update request could help to get the device data also
