### ISSUE TITLE
Warning in Logger at HA Startup

### ISSUE THREAD

**Issue by foxxcomm** [claudegel/sinope-gt125#60]
We see these in the System logs at each HA Startup. Looks fairly minor but thought you may want to have a look during next update cycle. Looks like it applies to both the Neviweb (sinope-1) and the gt125 versions of the integration.

Thank You for your great Sinope integrations!

--------------
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:361
integration: Climate (documentation, issues)
First occurred: 14:42:41 (2 occurrences)
Last logged: 14:42:44

Entity None (<class 'custom_components.sinope.climate.SinopeThermostat'>) implements HVACMode(s): off, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'sinope' custom integration

Entity None (<class 'custom_components.neviweb.climate.NeviwebThermostat'>) implements HVACMode(s): off, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'neviweb' custom integration

**Comment by claudegel** [comment]
Sorry didn't see your issue. Normally I receive an email about new issue but nothing this time.
This have been solve in my other custom components. I'll fix it soon.

**Comment by claudegel** [comment]
Ok I've created a new branch 
https://github.com/claudegel/sinope-gt125/tree/turn-0n-0ff
Only the file climate.py have changes
I still need to test on my side but if you want to test. replace your sinope/climate.py by the one in the new branch.

**Comment by claudegel** [comment]
On my side no error. Please test on your side before I merge

**Comment by foxxcomm** [comment]
Thanks for your work on this. I tested here and still seeing the following warning on HA startup. Wondering if this is your other plug-in for Sinope web however as I have both installed:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:363
integration: Climate (documentation, issues)
First occurred: 01:21:58 (1 occurrences)
Last logged: 01:21:58

Entity None (<class 'custom_components.neviweb.climate.NeviwebThermostat'>) implements HVACMode(s): off, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'neviweb' custom integration

**Comment by claudegel** [comment]
Ok I'll do the other one, neviweb, tonight and let you know when it is ready to test.

**Comment by claudegel** [comment]
Ok the other one is ready to test.
https://github.com/claudegel/sinope-1/tree/turn-on-off/custom_components/neviweb
only file climate.py have changed
Let me know if it work

**Comment by foxxcomm** [comment]
Tested and HA warnings at startup are fixed.

Thank You

**Comment by claudegel** [comment]
can you test the service climate.turn_off with on of your thermostats in the neviweb component to see if the thermostat will go off ?
if it work I'll push a release for neviweb and sinope.
Thanks for your help

**Comment by foxxcomm** [comment]
Tested under HA 2024.5.4 calling Climate: Turn Off and Climate: Turn on from Developer Tools -> Services:

Both functions do work in that I see the thermostat turn off on However: After clicking CALL SERVICE (both off and on), I don't see the CALL SERVICE button change color from BLUE to GREEN and display a check mark.

I then tested with my other climate entities and the CALL SERVICE button changes as expected to GREEN with a check mark. Guess is that your missing some confirmation call back to HA??

**Comment by foxxcomm** [comment]
Repeating the test with Log Viewer open, I'm seeing the following WARNINGS which may be related to this:


2024-05-23 20:53:39.834 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.neviweb_climate_masterbath is taking over 10 seconds
2024-05-23 20:53:40.202 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.neviweb_sensor_gt125 is taking over 10 seconds
2024-05-23 20:59:10.202 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.neviweb_sensor_gt125 is taking over 10 seconds
2024-05-23 21:00:56.792 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.neviweb_climate_masterbath is taking over 10 seconds
2024-05-23 21:10:10.205 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.neviweb_sensor_gt125 is taking over 10 seconds

**Comment by claudegel** [comment]
In your log you should see line like this
ATTR_SETPOINT_MODE:...
```
Data = {'onOff': 'off'}  <-- what we send
Request response = 200  <-- acknowledgement from Neviweb
Json Data received = {'onOff': 'off'} <--reply from Neviweb
```
Data is what is sent to Neviweb and the two other lines are what Neviweb reply. If you see this everything is fine.

**Comment by foxxcomm** [comment]
>> Can you check with sinope thermostats name instead of the neviweb thermostat name ?

Sorry, uninstalled the local sinope-gt125 version yesterday as I was running both of the plug-ins and only needed one – choose the online version as I have set back schedules setup in their online scheduler.
